git:
  depth: 1

branches:
  only: 
    - master
matrix:
  include:
    - stage: "Lint"
      language: node_js
      os: linux
      node_js: "8"
      script: cd src && npm run ci.tslint
    - stage: "WebPack and Build"
      os: osx
      env:
        - WebPackiOS="12.0"
      osx_image: xcode10.0
      language: node_js 
      node_js: "8"
      jdk: oraclejdk8
      before_script: pod repo update
      script:
        - cd demo && npm run build.plugin && npm i && tns build ios --bundle --env.uglify 
        - cd ../publish 
        - sh pack.sh
        - cp package/*.tgz ../demo-angular/package.tgz
        - cd ../demo-angular
        - sed -i -e 's/\"..\/src\"/"package.tgz"/g' package.json
        - npm i
        - tns build ios --bundle --env.uglify --env.aot
    - language: android
      env:
        - BuildAndroid="28"
        - Type="Angular"
      os: linux
      jdk: oraclejdk8
      before_install: nvm install 8.11.4
      script:
        - cd demo-angular && npm run ci.android.build
       
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository

before_install:
  - sudo pip install --upgrade pip
  - sudo pip install six

install:
  - npm install -g nativescript
  - tns usage-reporting disable
  - tns error-reporting disable
